<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Pages\Modules\Timesheet\Employee\Dashboard.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\Modules\Timesheet\Employee\Entry.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\Modules\Timesheet\Employee\Management.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\Modules\Timesheet\Employee\Report.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\Modules\Timesheet\Employee\Review.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\Modules\Timesheet\Employee\_ModalNewTask.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\Modules\Timesheet\Supervisor\Dashboard.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\Modules\Timesheet\Supervisor\Report.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\Modules\Timesheet\Supervisor\Review.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\Modules\Timesheet\Supervisor\Timesheet.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pages\Modules\PerformanceReview\Supervisor\" />
    <Folder Include="wwwroot\apps\modules\performance-review\css\" />
  </ItemGroup>

</Project>
