<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.5" />
    <!-- <Compile Remove="Pages\LeaveManagement\**" />
    <Compile Remove="Pages\NewFolder\**" />
    <Content Remove="Pages\LeaveManagement\**" />
    <Content Remove="Pages\NewFolder\**" />
    <EmbeddedResource Remove="Pages\LeaveManagement\**" />
    <EmbeddedResource Remove="Pages\NewFolder\**" />
    <None Remove="Pages\LeaveManagement\**" />
    <None Remove="Pages\NewFolder\**" /> -->
  </ItemGroup>

</Project>
