// <auto-generated />
using System;
using HRManagement.MsSQL.Base;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRManagement.MsSQL.Base
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRManagement.Domain.Models.Tables.EmergencyContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("emergency_contact_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedUtcDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedUtcDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("emergency_contact_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("emergency_contact_phone");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("emergency_contact_relationship");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmergencyContact", (string)null);
                });

            modelBuilder.Entity("HRManagement.Domain.Models.Tables.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("emp_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedUtcDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("emp_DOB");

                    b.Property<string>("EmployeeEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("emp_work_email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("emp_name");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("emp_gender");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("int")
                        .HasColumnName("emp_marital_status");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedUtcDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("emp_nik");

                    b.Property<string>("PersonalEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("emp_personal_email");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("emp_phone");

                    b.Property<string>("PlaceOfBirth")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("emp_POB");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("emp_role");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeEmail")
                        .IsUnique();

                    b.HasIndex("FullName")
                        .IsUnique();

                    b.HasIndex("Nik")
                        .IsUnique();

                    b.HasIndex("PersonalEmail")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("HRManagement.Domain.Models.Tables.EmployeeAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedUtcDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedUtcDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EmployeeAttachment");
                });

            modelBuilder.Entity("HRManagement.Domain.Models.Tables.EmployeeUpdateRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedUtcDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("emp_id");

                    b.Property<string>("HrReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("hr_reason");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedUtcDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewCurrentCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("new_current_city");

                    b.Property<string>("NewCurrentProvince")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("new_current_province");

                    b.Property<string>("NewCurrentStreetAddress")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("new_current_street_address");

                    b.Property<string>("NewCurrentZipCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("new_current_postal_code");

                    b.Property<DateTime?>("NewDateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("new_date_of_birth");

                    b.Property<string>("NewEmergencyContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewEmergencyContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewEmergencyContactRelationship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewFullName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("new_full_name");

                    b.Property<int?>("NewGender")
                        .HasColumnType("int")
                        .HasColumnName("new_gender");

                    b.Property<int?>("NewMaritalStatus")
                        .HasColumnType("int")
                        .HasColumnName("new_marital_status");

                    b.Property<string>("NewPersonalEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("new_personal_email");

                    b.Property<string>("NewPhoneNumber")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("new_phone_number");

                    b.Property<string>("NewPlaceOfBirth")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("new_place_of_birth");

                    b.Property<string>("NewResidentialCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("new_residential_city");

                    b.Property<string>("NewResidentialProvince")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("new_residential_province");

                    b.Property<string>("NewResidentialStreetAddress")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("new_residential_street_address");

                    b.Property<string>("NewResidentialZipCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("new_residential_postal_code");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("request_status");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeUpdateRequest", (string)null);
                });

            modelBuilder.Entity("HRManagement.Domain.Models.Tables.EmploymentInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedUtcDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("employment_department");

                    b.Property<string>("EmployeeDisplayId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("employee_display_id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("emp_id");

                    b.Property<int>("EmploymentStatus")
                        .HasColumnType("int")
                        .HasColumnName("employment_status");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("int")
                        .HasColumnName("employment_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedUtcDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("employment_position");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("employment_start_date");

                    b.Property<string>("SupervisorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("employment_supervisor_name");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeDisplayId")
                        .IsUnique();

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmploymentInformation", (string)null);
                });

            modelBuilder.Entity("HRManagement.Domain.Models.Tables.Lookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Lookup");
                });

            modelBuilder.Entity("HRManagement.Domain.Models.Tables.TimesheetDayComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ts_comment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ts_comment_text");

                    b.Property<DateOnly>("CommentDate")
                        .HasColumnType("date")
                        .HasColumnName("ts_comment_date");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("ts_comment_created_by");

                    b.Property<DateTime>("CreatedUtcDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ts_comment_created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("ts_comment_is_deleted");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("ts_comment_modified_by");

                    b.Property<DateTime>("ModifiedUtcDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ts_comment_modified_date");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int")
                        .HasColumnName("ts_comment_submission_id");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId", "CommentDate")
                        .IsUnique();

                    b.ToTable("TimesheetDayComments", (string)null);
                });

            modelBuilder.Entity("HRManagement.Domain.Models.Tables.TimesheetEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ts_entry_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUsed")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("ts_entry_app_used");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("ts_entry_created_by");

                    b.Property<DateTime>("CreatedUtcDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ts_entry_created_date");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("ts_entry_duration_minutes");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("ts_entry_employee_id");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("ts_entry_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("ts_entry_is_deleted");

                    b.Property<int>("Location")
                        .HasColumnType("int")
                        .HasColumnName("ts_entry_location");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("ts_entry_modified_by");

                    b.Property<DateTime>("ModifiedUtcDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ts_entry_modified_date");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("ts_entry_project_id");

                    b.Property<int>("ProjectLeadId")
                        .HasColumnType("int")
                        .HasColumnName("ts_entry_project_lead_id");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ts_entry_task_desc");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectLeadId");

                    b.HasIndex("EmployeeId", "EntryDate");

                    b.ToTable("TimesheetEntries", (string)null);
                });

            modelBuilder.Entity("HRManagement.Domain.Models.Tables.TimesheetProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ts_project_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("ts_project_created_by");

                    b.Property<DateTime>("CreatedUtcDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ts_project_created_date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ts_project_description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("ts_project_is_deleted");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("ts_project_modified_by");

                    b.Property<DateTime>("ModifiedUtcDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ts_project_modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ts_project_name");

                    b.Property<string>("ProjectLeader")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("")
                        .HasColumnName("ts_project_leader");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("ts_project_status");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TimesheetProjects", (string)null);
                });

            modelBuilder.Entity("HRManagement.Domain.Models.Tables.TimesheetSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ts_sub_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("ts_sub_created_by");

                    b.Property<DateTime>("CreatedUtcDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ts_sub_created_date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("ts_sub_employee_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("ts_sub_is_deleted");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("ts_sub_modified_by");

                    b.Property<DateTime>("ModifiedUtcDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ts_sub_modified_date");

                    b.Property<int>("Month")
                        .HasColumnType("int")
                        .HasColumnName("ts_sub_month");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int")
                        .HasColumnName("ts_sub_reviewed_by");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ts_sub_reviewed_date");

                    b.Property<string>("RevisionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ts_sub_revision_note");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("ts_sub_status");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ts_sub_submitted_date");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("ts_sub_year");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("TimesheetSubmissions", (string)null);
                });

            modelBuilder.Entity("HRManagement.Domain.Models.Tables.TodoTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("todo_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("todo_created_by");

                    b.Property<DateTime>("CreatedUtcDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("todo_created_date");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("todo_due_date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("todo_employee_id");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit")
                        .HasColumnName("todo_is_completed");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("todo_is_deleted");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("todo_modified_by");

                    b.Property<DateTime>("ModifiedUtcDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("todo_modified_date");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("todo_priority");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("todo_task_name");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "IsDeleted");

                    b.ToTable("TodoTasks", (string)null);
                });

            modelBuilder.Entity("HRManagement.Domain.Models.Tables.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedUtcDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("employee_email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedUtcDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("user_role");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeEmail")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HRManagement.Domain.Models.Tables.Employee", b =>
                {
                    b.OwnsOne("HRManagement.Domain.Models.Tables.Address", "CurrentAddress", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("emp_current_city");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("emp_current_province");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("emp_current_st_address");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("nvarchar(15)")
                                .HasColumnName("emp_current_postal_code");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employee");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("HRManagement.Domain.Models.Tables.Address", "ResidentialAddress", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("emp_residential_city");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("emp_residential_province");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("emp_residential_st_address");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("nvarchar(15)")
                                .HasColumnName("emp_residential_postal_code");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employee");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.Navigation("CurrentAddress")
                        .IsRequired();

                    b.Navigation("ResidentialAddress")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}




